version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: yemekhane_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: yemekhane
    ports:
      - "5433:5432" # <-- Burayı 5433 yaptık!
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: